name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: sigstore-python
        with:
          inputs: ./test/artifact.txt

  selftest-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifact and publish signature
        uses: ./
        id: sigstore-python
        with:
          inputs: ./test/artifact.txt
          staging: true

  selftest-glob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sign artifacts and publish signatures
        uses: ./
        id: sigstore-python
        with:
          inputs: ./test/*.txt
